.\" Manpage for testing.
.\" Contact brother-tolliver@tonism.thunder to correct errors or typos.
.TH man 8 "06 May 2010" "1.0" "testing man page"
.SH NAME
testing \- test great universe quetions - name 
.SH SYNOPSIS
nuseradd [nothing] -synopsis
.SH DESCRIPTION
Testing is a powerful script that answers the greatest question about our universe, how to write a man page? - description
.SH OPTIONS
There are no options because the universe is the universe - options
.SH SEE ALSO
useradd(8), passwd(5), nuseradd.debian(8)
.SH BUGS
No known bugs.
.SH AUTHOR
Brother Tolliver (brother-tolliver@tonism.thunder )
